### ISSUE TITLE
Item height or selectable display mode for library

### ISSUE THREAD

**Issue by NoDruid** [mcpierce/comixed#2]
I added a comic to the library the entry height would remain the size of the text, so that I'm not able to see the complete cover, just a little part of it. Which could not even be the cover at all put a page further into the comic, not entirely sure.

**Comment by mcpierce** [comment]
So, for something like this, you don't necessarily want to make the row height changeable, but instead would like to have some sort of a thumbnail for the cover displayed, yeah?

**Comment by mcpierce** [comment]
Another thought is that the details view column might not be the right place to display the cover. I'm considering adding a hover view that will show the cover when the mouse is over an entry.

**Comment by NoDruid** [comment]
> So, for something like this, you don't necessarily want to make the row height changeable, but instead would like to have some sort of a thumbnail for the cover displayed, yeah?

I agree, thinking this over I also think just changing the row height to fit the cover would be worng.

> Another thought is that the details view column might not be the right place to display the cover. I'm considering adding a hover view that will show the cover when the mouse is over an entry.

I think so, too. In the way thinks are currently displayed, the cover can be removed. But I think you have to rethink the way how and what you want to display. Because the same way, the cover is currently incompletely displayed, also the fields locations and summary are not completely readable when filled. In its current form, I think only Series Name, Volume, Publisher, Added, Last Read, Issue, Pages and Format make sense, because they all can fit in a single row with limited spacing. But maybe there is a mistake in my way of thinking. If you are willing to share, I would be very interested to hear, how you imagined the way the library should be displayed in your program. Also I must apologize in advance, english is not my native language, so i might make mistakes here and there.

**Comment by mcpierce** [comment]
I can see your point, though the app can be changed so that hovering over the description, for example, would show the full description as a popup tool tip. The same with other fields, like notes and writers, etc.

I think for now, though, maybe a different approach could work. Maybe a bar (which could be shown/hidden) along the bottom of the main window could show the covers for the comics in the details view. Then when you select a row in the table, that comic's cover would be moved to the center of that bar at the bottom. So that way you could see the cover in the context of the details view; i.e., the selected one is larger, while the ones before and after it are on the left and right and slightly smaller.
