### ISSUE TITLE
Scrapped comics info link to comicvine

### ISSUE THREAD

**Issue by theotocopulitos** [mcpierce/comixed#256]
For those comics scrapped from comicvine, a custom field (or by default use AND display the info field) to include the www link to the comicvine page.

**Comment by mcpierce** [comment]
Currently there are two fields in the comics table: **comic_vine_id** and **comic_vine_url**. I had considered dropping the latter for the former since you can generate the latter using the former value.

Are you wanting to have this field exposed in the comic details page? If so, what do you think of adding that to #205 on the **Credits** page? If the value is present, then include a link there reading:

Data retrieved from [ComicVine](http://comicvine.gamespot.com).

**Comment by mcpierce** [comment]
What I'm going to do is add a link to the comic details page that goes to the ComicVine page to show the info for the issue.
