### ISSUE TITLE
ComicVine id not being / needs to be imported from ComicInfo.xml

### ISSUE THREAD

**Issue by bareheiny** [mcpierce/comixed#460]
Apologies, not sure if this is a bug or feature request.

When importing a comic file, the ComicVine id (if saved) is not being read in.  This means that a user needs to re-scrape the issue if information is missing or updated.

Potential sources of the field in a comic scrapped via ComicRack:

<Notes>Scraped metadata from ComicVine [CVDB109827] on 2018.07.31 21:08:22.</Notes>
<Web https://comicvine.gamespot.com/newuniversal-6-tumble/4000-109827/ </Web

had to remove the ">"

**Comment by mcpierce** [comment]
Since the data's buried in a comment rather than set in an explicit field, I feel it's probably not safe to scrape it out of the comment. The field is explicitly set in CX when it scrapes the comic as a way of knowing CX did the work, sort of an explicit way of saying "This comic has not been scraped".

**Comment by bareheiny** [comment]
Fair call.  The note field could contain any information.

The <web> field may be more appropriate?

**Comment by mcpierce** [comment]
It's a potential source for it. Though the web link's not necessarily a CV-related field.

**Comment by mcpierce** [comment]
Given that the field's not specific for CV, I'd be hesitant to do that. I think ultimately it would be better for users to import the existing metadata and then let the CX scraping engine do the rest.

Actually, a thought for a new feature would be to have CX do *just* a CVID fetch for all comics in the library that don't have one. Kind of like a scrape but, instead of getting all of the metadata, it would let the library determine *only* the CVID and set it for each comic. Maybe during import? It would slow down that process but would be a great way to get it into a good initial state.

**Comment by bareheiny** [comment]
Would there be accuracy issues?

I'm not thinking that this could be a candidate for a plug-in.  A plug-in could scan the note or web fields and populate the CX DB CVID field from there.  A plug-in would require a user to explicitly find, install and run it...and it could be made clear that the CVID could be incorrect if it's not contained in the fields used by the plug-in.

**Comment by mcpierce** [comment]
I think that'd be better as a plugin.

If it were a core feature of the import process, then that would require me to support processing that field in the XML file and all the possible values it could have. And if there's an issue, it'd be a bug against the core project.

Also, given that it's mostly likely a one-time action (I don't imagine people maintaining comics in CR and then importing comics into CX many times) I'd rather have someone else take on that processing as a plugin.

**Comment by bareheiny** [comment]
Dammit.  My post comment should have said "I'm thinking that this would be a candidate for a plug-in".

Anyhoo, yes - this would be a one-time action, so a plug-in, script of SQL query would be more than sufficent to get this done.
