### ISSUE TITLE
Replace the current library state code with a more streamlined version

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#484]
The existing library state code is pretty resource intensive; i.e., it loads the full comic details, including the image content, when fetching either the initial state on startup or deltas as the application runs.

What's needed is a more streamlined system that fetches only the minimum amount of data for the list and gets the full details of a comic when it's opened and displayed.

Relates to #259, #415, #459, #473 and #480.

## Acceptance Criteria
1. Add a **deleted** field to the **comics** table and data models.
1. New, or refactored, REST API endpoints will include:
   1. Get the list of comics added/updated since a specified timestamp.
      1. Includes the library's import and rescan status.
   1. Get the details for a single comic by ID.
   1. Update the details for a single comic by ID.
   1. Purge deleted comics from the database.
      * An optional remove flag indicates that it should also delete the file from disk.
1. Comic pages are cached outside of the archive file after first retrieval for faster access.
   1. The caching mechanism will use a weak hash to conserve memory.
1. When retrieving the list of comics added/updated, the response will include:
   1. the set of comics added or updated since the timestamp,
   1. the set of comic IDs that have been removed,
   1. the number of comic imports that are pending, and
   1. the number of comics left to be rescanned.
1. When retrieving the details for a single comic,, the full data model is returned.
1. When deleting a comic from the library:
   1. the **deleted** flag is set, and
   1. the comic file itself is untouched.
1. When purging a comic from the library:
   1. the record is removed from the database, and
   1. if the remove flag is set, the comic file is deleted from disk as well

**Comment by bareheiny** [comment]
Looking forward to this!

#473 still appears to be an issue unfortunately, even with increasing the max memory available for Java.  Although this may be due to the file size rather than the page count.  A 400+ page file that's a little under 1GB takes 86 minutes to import....over 1GB seems to fail.

**Comment by mcpierce** [comment]
@bareheiny Part of what I'm planning for the backend should alleviate that memory usage by preventing it from loading and holding onto all of the image data as comics are processed. It'll hopefully also fix the slowness during import as well.

**Comment by mcpierce** [comment]
Some of the work for simplifying the APIs was done in #509 while moving the code into the LibraryModule. But there is still work to be done to make the APIs smaller

**Comment by bareheiny** [comment]
Hit the out of memory issue again today, while trying to import the remainder of my library.

I'm wondering if storing cover images outside of archives would help alleviate load times, and memory usage.

I've noticed that applications like ComicRack and YAC seem to extract and store cover images (I assume the first image in the file...but can't confirm that).

Having the covers extracted as part of the import process (for example) would - I assume - mean that a library or comic load would only require grabbing data from the H2 database, rather than opening the archive file.  Personally, I'd happily trade increased disk space usage for faster loading times.

Of course, I could be way off track here - I'm still trying to understand the code (no java experience at all...so I'm pretty much a monkey with a hammer).

**Comment by mcpierce** [comment]
I've been thinking about that, though I think I'd rather setup a caching directory and store the images by hash rather than stick them into the database. That way we can quickly search for a cached image (it's only disk access time involved) and, if it's found, return it. Otherwise extract it, cache it and return the image.

That all said, I'm also wanting to rewrite the whole import code to try and speed things up considerably. The first pass I wrote about 3 years ago and wasn't written with efficiency in mind. What I'm considering is to have the import system literally just create a record in the comics table and nothing else. Then a worker thread can run in parallel and look for comics that are only partially imported (either which have no Page records or else have a flag set) and do the full import (hash the pages, tag blocked pages, etc.) It would significantly speed up that process to go that route.

My only fear is that a comic gets into a weird state where it's not fully imported but the app doesn't know for some reason. Maybe something like, after a comic is fully imported, the system stores a hash of the comic file itself into the comics table? Then we could use that hash as a way of also checking if the comic's ComicInfo.xml file has been updated; i.e., if you change the details on a comic (scrape it, change the imprint or other detail) then we either erase the hash or do something else that triggers the rescan/update code.

Any thoughts on that?

**Comment by bareheiny** [comment]
Doh...as usualy, I wasn't paying attention to how clear my comment was!

CR and YAC store the images in an directory (thinking about it, I'm pretty sure Ubooquuity does the same).  When I mentioned grabbing data from the DB, I should have specified the metadata stored - such as title and so on...not the actual image.  Adding images to DBs makes me nervous.

The file hash was requested by another user as well I think - so that would likely address two issues.  I wouldn't be adverse to the import process having a quick peek at the file during import, and recording the number of files contained...that may be another way to allow checking for partial / incomplete imports.

**Comment by bareheiny** [comment]
It occurs to me to ask - where is the first major pain point when using CX?

The import process?  Eh...sort of, but not really.  Once you understand that CX is checking each comic and creating hashs for the pages, you can get past the slow import process.  I suspect it'll be the major point for making CX stand out from other options.  It's also a one off type thing (theoretically).  I'm not going to be importing 50k of comics each week.

Loading a large library for use once the import has been completed?  Yes...for me, right now.  Each "get" becomes slightly slower (on average)...from around 500ms, the time seems to have settled around 2.5seconds (at around 20k loaded).

But I'm a single user...I'm not sure a sample of 1 is enough to be making any concrete decisions on :)


Also thinking about memory - is it correct to think that the max memory available needs to be slightly more than the size of the largest comic being imported?  2GB works fine...and I've got a few 1.5GB issues.  Dropping it below 1GB causes immediate issues on import - usually around the time the import strikes the large files.

**Comment by mcpierce** [comment]
I've been wondering why that (slowing down after incrementally access comics) would cause memory usage to go up. I can't think of where that would be since nothing's holding onto the comic references; i.e., when the request comes in to, say, get a page, the call chain is controller -> service -> repository, gets a Comic object, extracts the image content, and returns. Nothing holds onto the Comic, so that memory ought to be immediately released. Unless there's a memory leak in one of the dependencies, such as the Apache compression code, I would really like to know what's lingering and sucking up memory.

**Comment by bareheiny** [comment]
I'm recording the network activity now (hopefully it doesn't fail again - the recorder that is, not CX).

So far, the library has updated with 12,900 comics...and it's definitely slowing down - the time between increment of 100 is increasing noticeably.  

Memory usage (via Task Manager) is ranging between 70% and 90%, but I do have some other stuff going on in the background.  If there was some sort of leak, I'd expect the usage to keep increasing and then stablise when CX ran hit the 2GB limit I've imposed.

I do wonder if my striking the memory issue earlier was due to the library updating AND trying to import comics.

My intention is to wait for CX to finish updating (at around 42k), and then attempt to import the remaining 10k issues.

Although I'll likely throw something if I find the network activity recorder (the third I've tried) fails or closes prematurely.

**Comment by bareheiny** [comment]
The network activity recorder failed again - but it took somewhere around 2 to 3 hours for the library to load fully.

I'm now importing the remaining ~10k of comics.  The processing time per page felt slow...but it seems to have picked up slightly.  Note that this is purely a gut feel...unfortunately (for now) I have no data to back it up.

**Comment by mcpierce** [comment]
@bareheiny Are you going to hate me if I tell you that I'm working on #559 which is going to require recreating the database? 😞 

I've got some ideas for improving all of that performance and it requires a revamp to the DB. And I'm finding Liquibase to be easier to use for this than Flyway, so wanted to take this opportunity to switch over.

**Comment by bareheiny** [comment]
Well, I've imported my library ,partially and fully, multiple times...doing it any number of times again won't casue me any issues :)

I got the remaining issues imported overnight - so it looks like the memory issues I struck were due to the library refreshing and running an import.  I've got the activty log running again...as I really want to have a look a the data - theres no point in my saying it's slowing down if I can provide any evidence that it actually is.

**Comment by bareheiny** [comment]
Found a better logger - the library update is still running, but so far it looks like the actual "get 100" process is only taking a second or two...not too shabby.

BUT...the time between each "get 100" is slowly increasing from a second or two to 1min 30 seconds.  So far 479 gets have run...the average time to between each on is 30 seconds...so that's around 4 hours, just on waiting for the library to populate.

Will have a proper look at the data once I have a full log, and get some time tomorrow.

**Comment by mcpierce** [comment]
You mean the time between when the backend receives the GET and when it returns a response is slowly growing? Hrm, I wonder if it's related to fetching data based an an unindexed field (the addedDate)?

I have a ticket to switch that to using the lastUpdatedDate field instead (#557) and I think that, with the ticket I'm working on (#559), I'll add indexing to that field. Would you have some cycles to test out such a change before it's committed?

**Comment by bareheiny** [comment]
I think that's what I'm saying!

Essentially, the logs look something like this:

11:59 00:00:00 - Start CX
11:59 00:00:00 - Ask for password
12:00 00:00:00 - Generate token
12:02 00:00:00 - User
12:04 00:00:00 - Initial GET 100, returns in 2 seconds
12:04 00:01:00 - 2nd GET 100, returns in 2 seconds
12:04 00:02:00 - 3rd GET 100, returns in 2 seconds
…
02:04 00:00:00 - 287th GET 100, returns in 2.5 seconds
02:04 00:30:00 - 288th GET 100, returns in 2.5 seconds
…
04:00 00:00:00 - 511th get 100, returns in 7.2 seconds
04:01 57:00:00 - 512 get 100, returns in 10 seconds

At this point, all comics are loaded, and things start to settle down (GET 100 return no new records, are run every 100ms or so with no issue).

BUT...it took around 17 minutes to settle down.  It was taking about 1 GET 100 a minute to return nothing.  Although these 17 runs only return 395 bytes...once it settled down, 503 bytes were being returned.

I actually wasn't expecting to see the GET return time to increase as much as it did...although that tends to fluctuate depending on the amount of data.  The bigger concern (atm) is the time between GETs increasing.


Happy to do further testing - just let me know what you want done, and what I need to get CX ready :)

**Comment by mcpierce** [comment]
So I just merged the changes for #559 today (but Travis-CI is being weird again and failing the build after the build's finished successfully) and added indexing for both the added and last updated dates on comics. So this first change should hopefully fix that linear growth in update times and make it much faster.

**Comment by bareheiny** [comment]
All compiled, and running an import now.  Once that's done, I'll check the library load times again :)

**Comment by mcpierce** [comment]
> All compiled, and running an import now. Once that's done, I'll check the library load times again :)

Sounds good. I just pushed the changes for #557 so the updates are using the last updated date rather than last added date when getting updates. That should produce some small improvement on load times.

**Comment by bareheiny** [comment]
No luck I'm afraid...the time between GET 100 requests is increasing - from around 1 second to 1 minute.

I've only imported around 23k comics when I did this check - I suspect the results will be worse once I imported the other half of my library.

What happens once 100 comics have been retrieved?  That seems to be where the issue is....the only visual queue that the loads are slowing down is the doughnut chart updating - which is why I initially thought that was the issue.

**Comment by mcpierce** [comment]
The donut chart would slow down because it's doing statistics for more comics, and I don't think PrimeNG expected it to be a real-time display. But I wouldn't use that as a gauge for the library update speed since it updates after the data is received and separately from the update code.

The flow for updates is as follows:

1. First pass the browser sets the latest updated date it has to 0; i.e., n=0
1. Browser sends request to the backend and says "give me all updates since n" (first pass).
1. Backend sends a maximum of 100 comics with last updated dates greater than 0 (1/1/1970).
1. Browser merges those 100 comics into its list of comics.
1. Browser finds the most recent latest update date from the comics it has; i.e., n=12345
1. Go to step 2 above.

I would think the unavoidable bottleneck for processing would be the merging the browser side since, when it merges the comics its received, it has to filter out any existing entry that's being updated by an incoming comic before adding those received comics to its list. But that's not a terribly slow process and, more importantly, it runs separately from the actual requests to get updates. So updates should be running even as the update is processed.

**Comment by bareheiny** [comment]
Hmmm.  So I *think* what I'm seeing in the logs is this:

2.  Browser sends request to the backend and says "give me all updates since n" (first pass).
3.  Backend sends a maximum of 100 comics with last updated dates greater than 0 (1/1/1970).
6.  Go to step 2 above.

I'm not seeing steps 4 and 5 - obviously because it's happening outside of Chrome activity.  But this seems to be where the slowdown is occuring.

Would it be possible / appropriate to have a slightly different way of fetching the library data on the initial load - say using a static value such as the ID from the comic table?  That would (I assume) remove the need for a merge type process, as it would be a simple append.

Once the initial load is done, then go back to using the update time.


Essentially the problem I'm striking is that it's taking upwards of an hour (possibly less....I forget exactly, and am rebuilding my Suface so don't have access to the old logs atm) for the intial library load.  Meaning I can't really do anything meaninginful in CX for some time after starting it.

**Comment by mcpierce** [comment]
I'll have to look at how we can improve that initial load. Though I'm afraid if we overcomplicate loading then it'll become nearly impossible to maintain. Like Scotty said, "The more complicated the plumbing, the easier it is to stop up the drain."

I think if it comes down to it, we might have to instead go to a paging system where the frontend requests only those comics for the current view. The problem there is it will push a lot of display knowledge into the backend, which is a Bad Thing (tm) since I don't think it's a benefit to push that into the backend.

I'd like to, before we go too far away from how the load is now, see if the new direction for loading and importing goes. I pushed the changes to #544 this afternoon and, for me, importing 10k+ comics took under a few minutes, and the processing on the backend ran while I was able to interact with the library.

**Comment by bareheiny** [comment]
Importing 50k+ comics took 40ish minutes.  So I logged out, and back in to see what happens...the inital load is trucking along insantely quikcly.  49k and counting, with no sign of slowing down yet.

Huh.  50600 imported, and it starts slowing down - as soon as new (i.e. populated) publishers exist (I'm sitting on the doughnut chart page).

**Comment by mcpierce** [comment]
Again, I'd just ignore the donut. It's not doing any calculations: it only refreshes after comics have been retrieved. I don't know that that widget (it comes from [PrimeNG](https://www.primefaces.org/primeng/#/chart/doughnut) is necessarily very efficient at providing real-time updates.

I'm sure once it hits that upper limit is when the processing kicks in on the backend. When you say "slowing down", what specifically do you mean? The overall app slows down, or something else? I still have one more feature to implement (#510) to make the library update less chatty. Right now the request gets an immediate response if the number of comics to be processed or rescanned are greater than 0. Which obviously makes it return with no actual comic updates. What I'm going to do is have the request include the number of comics to be processed or rescanned from the last update and, if that number hasn't changed, to sit on the request until a comic is updated (which will change those values) or until the timeout period passes.

**Comment by bareheiny** [comment]
The donut gets my focus because it's the most obvious visual representation that something's going on (or in this case, slowing down).  I can see the same behaviour in the "There are XXXX comics in the library" on start up and log in.

Essentialy "There are XXXX comics in the library" goes 0,100,200,300,500,600..and so on...50000,50100....50200.....50300.....50400.  At the same time, the donut chart is being refreshed...with the same frequency.

From 0 to 50100 the increases are happening about once every half second.  Around 50100 the mark the time between increases...well, it increases.  The only visual queue that something is different is the donut chart...at 50100 publishers (or teams, or characters etc) are being found - so the chart is being updated with the approprate percentages.

My main concern here is that with no metadata loaded, I'd be looking at having the "There are XXXX comics in the library" fully updated in around 2 to 3 minutes.  In the previous CX build (prior to the new import process) I'd be looking at around 4 hours.


While the comic count is being populated, I find CX sluggish - as if whatever action I've selected is waiting for the "GET 100"s to be completed.   I suspect this sort of thing would be resolved by your plan to make the library update less chatty....but it'd be ideal not to have to wait 4 hours for the library to be populated.  Note that when the "GET 100"s aren't returning changes, and still firing every 100ms or so, CX runs fine.  The sluggishnesh seems to occur during the intial load.


Is it at all possible to disable the chart - and whatever process is providing it with the data?  If I can see that disabling it has no impact on the library update time, then I'll shut up about it.

**Comment by bareheiny** [comment]
Just did a screen record - had to zip it as GitHub doesn't support attaching mp4 files...and it was around 234MB anyways.

There are a few slow downs, likely due to other CX activity happening in the background - and accessing CX from another machine (same network, but via wifi), but even with those the refresh is pretty quick.  The slow down becomes more obvious around the 2:55 mark.

In older builds (and I'm going to assume the current build...once more comics have been fully processed), the slow down becomes worse the more comics have been loaded.

[CX - library load on start.zip](https://github.com/mcpierce/comixed/files/3726646/CX.-.library.load.on.start.zip)

**Comment by mcpierce** [comment]
@bareheiny You can "disable" the donut by just going to any other page; i.e., it's only updated when you're sitting on the home page. So try navigating to one comic's details page and watch things.

**Comment by bareheiny** [comment]
Will give that a try once CX has finished the second part of the import process.

**Comment by mcpierce** [comment]
Closing this story now that #553 is merged.
