### ISSUE TITLE
Sorting a series by issue number seems to be treating the issue numbers as strings

### ISSUE THREAD

**Issue by wyldphyre** [mcpierce/comixed#503]
**Describe the bug**
I have a series (Ah! My Goddess) that has over 300 issues. When I drill down into the series and sort by issue number, it appears to be treating the issue numbers as strings instead of numbers, so it goes 1, 10, 100, 101, 102, etc.

**To Reproduce**
1. Drill down into a collection with issue numbers, and more than 100 issues
2. Set sort order to `Sort by issue#`
3. Ordered list is 1, 10, 100, 101, etc

**Expected behavior**
All comic issue numbers that *are* numbers should sort numerically, not as if they are strings. Any issue numbers that cannot be treated as a number for some reason, should come after.

- Decimals should be handled correctly. i.e. 13, 13.1, 13.2 (some manga can be listed this way)
- It would be nice if an attempt could be made to handle things like 13a, 13b etc, though that would just be a bonus :).

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.5
 - Browser: Safari
 - Version: 0.4.0-20190728180804

**Comment by mcpierce** [comment]
Added a sortable_issue_number field to the Comic interface and changed sorting to use that field instead. The field is a string (since issue #s are not guaranteed to be numeric) and is left-padded to make all issue numbers uniform in length so that sorting is improved.

There will likely still be edge cases where sorting is less than perfect, such as Marvel's tendency to add suffixes to issue numbers for story arcs and DC's point issues. But in those cases the issues will fall either before or after the remaining set of comics when sorted by issue. And to view comics in a proper order by release, it's better to use the cover date instead.

If this fixes the bug for you, please close this ticket. And thank you!

**Comment by wyldphyre** [comment]
Sorry, but this doesn't look like it helped with the Series problem. I cloned the repo, switch to "release/0.4.0" and used the build process to build and run a new jar file, and it doesn't appear to have changed anything. I even started with a fresh database.

When importing a couple of my "Analog" comics as test samples they were each given the Series of "Analaog 001" and "Analog 002", which looks like it came from the file name.

However, the Credits and Story info *did* import fine.

**Comment by wyldphyre** [comment]
Sorry, but this doesn't look like it helped I cloned the repo, switch to "release/0.4.0" and used the build process to build and run a new jar file, and it doesn't appear to have changed anything. I even started with a fresh database.

I imported a manga series (Ah My Goddess) and it gave every archive the correct series and issue number, but drilling into the series and sorting by issue number still doesn't work.

**Comment by mcpierce** [comment]
What order do you see when sorting? Is it still doing the previous behavior, or is the sorting doing something else?

**Comment by wyldphyre** [comment]
Cool. I'll try to test it later today.

**Comment by wyldphyre** [comment]
I can confirm that this sorting problem is fixed now.
