### ISSUE TITLE
Do not return immediately if the number of imports or rescans hasn't changed since the last update

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#510]
When an import is in progress, the update request always returns immediately, even if the number of imports hasn't changed.

Instead, the backend should wait until an update (or the timeout is reached) if the import count is greater than zero. This will reduce the number of requests from the frontend.

**Comment by mcpierce** [comment]
Apparently the extreme chattiness of the old code is a huge contributing factor in how slow the import process ran. By fixing this, my local test imports are way faster.

**Comment by bareheiny** [comment]
Weirdly, the change makes the inital phase of the import process (import with / without metadata has been selected) *seem* slower - but this is purely due to the number to be imported increasing in fits and starts, rather than incrementally.

Does the progres bar impact performance at all?  I'd not be adverse to it being removed...

I would be happy with a % under the "IMPORTING XXXX FILES...", something that gives me a better idea of progress.

**Comment by bareheiny** [comment]
Ahh...it took a while, but I realised I won't notice any change here - I log out of CX once an import has started, and keep an eye on the log file to gauge progress.

**Comment by mcpierce** [comment]
No, the progress bar isn't tied to the backend process at all. It's just a spinner in the browser to so the app doesn't look dead since you can't start a new import while files are being processed.

We can't really show a percentage completed since we don't keep track of how many comics were submitted for import. That's why it just outputs the number of comics remaining instead.
